#!/usr/bin/env python3
"""
Collects every image a page says it still needs into `docs/IMAGES-NEEDED.md`.

    python3 site/scripts/build-image-list.py

The list is generated, never hand-maintained: a shot list typed out by hand goes
stale the first time someone adds a placeholder and forgets the index, and a
stale shot list is worse than none — it sends you out to photograph things that
already shipped.

Two things count as "needed here":

- A rendered `<ImagePlaceholder alt="...">`, which is the one to use. It shows a
  dashed box on the page, so the gap is visible to a reader and to the author.
- A legacy `{/* Photo needed — ... */}` MDX comment. These render as nothing at
  all, which is how seven of them sat unnoticed. They are listed so they can be
  converted, and this script is what finds them.

Filing a photo: drop it in `projects/<slug>/images/`, then replace the
placeholder with a normal image reference carrying the alt text listed here.
"""

import glob
import os
import re
import sys

PLACEHOLDER = re.compile(
    r'<ImagePlaceholder\s+alt="([^"]+)"[^>]*>\s*(.*?)\s*</ImagePlaceholder>', re.S
)
LEGACY = re.compile(r'\{/\*\s*Photo needed\s*[—-]\s*(.*?)\s*\*/\}', re.S)
LEGACY_ALT = re.compile(r'alt text when it lands:\s*(.*)$', re.S)


def collapse(text):
    """MDX wraps prose across lines; a table cell needs it on one."""
    return ' '.join(text.split())


def shots_in(page):
    """Every image the page asks for, as `(alt, note, style)`."""
    body = open(page, encoding='utf8').read()
    found = []

    for match in PLACEHOLDER.finditer(body):
        found.append((collapse(match.group(1)), collapse(match.group(2)), 'placeholder'))

    for match in LEGACY.finditer(body):
        note = collapse(match.group(1))
        alt = ''
        if hint := LEGACY_ALT.search(note):
            alt = collapse(hint.group(1))
            note = collapse(note[: hint.start()])
        found.append((alt or '_needs alt text_', note, 'invisible comment'))

    return found


def main():
    root = os.path.dirname(os.path.dirname(os.path.dirname(os.path.abspath(__file__))))
    os.chdir(root)

    pages = {}
    for page in sorted(glob.glob('projects/*/index.mdx')):
        if shots := shots_in(page):
            pages[page.split('/')[1]] = shots

    total = sum(len(shots) for shots in pages.values())
    legacy = sum(1 for shots in pages.values() for shot in shots if shot[2] == 'invisible comment')

    lines = [
        '# Images still needed',
        '',
        '<!-- Generated by site/scripts/build-image-list.py — do not edit by hand. -->',
        '',
        f'**{total} photos across {len(pages)} projects.**',
        '',
        'Save each one into `projects/<slug>/images/`, then replace the placeholder',
        'on the page with the image, using the alt text given here — it is written to',
        'be copied rather than reworded.',
        '',
    ]

    if legacy:
        lines += [
            f'{legacy} of these are still `{{/* Photo needed */}}` comments, which render',
            'as nothing at all — a reader cannot tell the page is missing a photo, and',
            'neither can you. Converting one to `<ImagePlaceholder>` makes the gap visible.',
            '',
        ]

    for slug, shots in pages.items():
        lines += [f'## {slug}', '', '| What to shoot | Alt text to use | Status |', '|---|---|---|']
        for alt, note, style in shots:
            lines.append(f'| {note or "—"} | `{alt}` | {style} |')
        lines.append('')

    os.makedirs('docs', exist_ok=True)
    with open('docs/IMAGES-NEEDED.md', 'w', encoding='utf8') as out:
        out.write('\n'.join(lines))

    print(f'docs/IMAGES-NEEDED.md — {total} photos across {len(pages)} projects')
    return 0


if __name__ == '__main__':
    sys.exit(main())
